import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getSession } from 'next-auth/react'
import { Session } from 'next-auth'

type PrivateProps = {
  session: Session | null
}

const Private: NextPage<PrivateProps> = ({ session }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Private Page
        </h1>
        <p>
          Hello! {session?.user?.name}
        </p>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getSession({ req: ctx.req })
  console.log(session)
  return { props: { session } }
}

export default Private
