name: reviewdogPrettier
on: pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: volta install node
      - run: volta install pnpm
      - run: pnpm i --frozen-lockfile
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-pr-review
          prettier_flags: 'src/ test/'
