name: typeCheck

on:
  pull_request

permissions:
  contents: read

jobs:
  typeCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: volta-cli/action@615a78f6c83e116339c53b94f3f82b4d6c0b7d18 # v5
      - run: yarn install --immutable
      - run: yarn db:generate
      - run: yarn typeCheck
